// Code generated by mockery v2.40.0. DO NOT EDIT.
// Re-generate with: go generate ./...

package scraper

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockHTTPClient is a mock implementation of HTTPClient.
//
// To use it in tests:
//
//	m := scraper.NewMockHTTPClient(t)
//	m.EXPECT().Do(req).Return(resp, nil)
type MockHTTPClient struct {
	mock.Mock
}

// MockHTTPClient_Do_Call holds expectations for a single Do call.
type MockHTTPClient_Do_Call struct {
	*mock.Call
}

// Do is the mock implementation of HTTPClient.Do.
func (_m *MockHTTPClient) Do(req *http.Request) (*http.Response, error) {
	ret := _m.Called(req)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(*http.Request) *http.Response); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHTTPClient_Expecter provides the type-safe EXPECT() API.
type MockHTTPClient_Expecter struct {
	mock *mock.Mock
}

// EXPECT returns a MockHTTPClient_Expecter for setting up type-safe expectations.
func (_m *MockHTTPClient) EXPECT() *MockHTTPClient_Expecter {
	return &MockHTTPClient_Expecter{mock: &_m.Mock}
}

// Do sets up an expectation for HTTPClient.Do.
func (_e *MockHTTPClient_Expecter) Do(req interface{}) *MockHTTPClient_Do_Call {
	return &MockHTTPClient_Do_Call{Call: _e.mock.On("Do", req)}
}

// Return configures the return values for a Do expectation.
func (_c *MockHTTPClient_Do_Call) Return(resp *http.Response, err error) *MockHTTPClient_Do_Call {
	_c.Call.Return(resp, err)
	return _c
}

// RunAndReturn configures a function to run when Do is called.
func (_c *MockHTTPClient_Do_Call) RunAndReturn(run func(*http.Request) (*http.Response, error)) *MockHTTPClient_Do_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHTTPClient creates a new MockHTTPClient with test cleanup registered.
func NewMockHTTPClient(t interface {
	Cleanup(func())
	FailNow()
	Errorf(format string, args ...interface{})
	Logf(format string, args ...interface{})
}) *MockHTTPClient {
	mock := &MockHTTPClient{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
