// Code generated by mockery v2.40.0. DO NOT EDIT.
// Re-generate with: go generate ./...

package scraper

import (
	"context"

	"github.com/ducminhgd/manga-chef/pkg/sources"
	mock "github.com/stretchr/testify/mock"
)

// MockScraper is a mock implementation of ScraperInterface.
//
// To use it in tests:
//
//	m := scraper.NewMockScraper(t)
//	m.EXPECT().GetChapterList(ctx, "https://...").Return(chapters, nil)
type MockScraper struct {
	mock.Mock
}

// MockScraper_GetChapterList_Call holds the expectations for a single
// GetChapterList call.
type MockScraper_GetChapterList_Call struct {
	*mock.Call
}

// GetChapterList is the mock implementation of ScraperInterface.GetChapterList.
func (_m *MockScraper) GetChapterList(ctx context.Context, mangaURL string) ([]sources.Chapter, error) {
	ret := _m.Called(ctx, mangaURL)

	var r0 []sources.Chapter
	if rf, ok := ret.Get(0).(func(context.Context, string) []sources.Chapter); ok {
		r0 = rf(ctx, mangaURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sources.Chapter)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, mangaURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChapterList sets up expectation for ScraperInterface.GetChapterList.
func (_e *MockScraper_Expecter) GetChapterList(ctx interface{}, mangaURL interface{}) *MockScraper_GetChapterList_Call {
	return &MockScraper_GetChapterList_Call{Call: _e.mock.On("GetChapterList", ctx, mangaURL)}
}

// Return configures the return values for a GetChapterList expectation.
func (_c *MockScraper_GetChapterList_Call) Return(chapters []sources.Chapter, err error) *MockScraper_GetChapterList_Call {
	_c.Call.Return(chapters, err)
	return _c
}

// RunAndReturn configures a function to run when GetChapterList is called.
func (_c *MockScraper_GetChapterList_Call) RunAndReturn(run func(context.Context, string) ([]sources.Chapter, error)) *MockScraper_GetChapterList_Call {
	_c.Call.Return(run)
	return _c
}

// MockScraper_GetImageURLs_Call holds the expectations for a single
// GetImageURLs call.
type MockScraper_GetImageURLs_Call struct {
	*mock.Call
}

// GetImageURLs is the mock implementation of ScraperInterface.GetImageURLs.
func (_m *MockScraper) GetImageURLs(ctx context.Context, chapterURL string) ([]string, error) {
	ret := _m.Called(ctx, chapterURL)

	var r0 []string
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, chapterURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, chapterURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetImageURLs sets up expectation for ScraperInterface.GetImageURLs.
func (_e *MockScraper_Expecter) GetImageURLs(ctx interface{}, chapterURL interface{}) *MockScraper_GetImageURLs_Call {
	return &MockScraper_GetImageURLs_Call{Call: _e.mock.On("GetImageURLs", ctx, chapterURL)}
}

// Return configures the return values for a GetImageURLs expectation.
func (_c *MockScraper_GetImageURLs_Call) Return(urls []string, err error) *MockScraper_GetImageURLs_Call {
	_c.Call.Return(urls, err)
	return _c
}

// RunAndReturn configures a function to run when GetImageURLs is called.
func (_c *MockScraper_GetImageURLs_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *MockScraper_GetImageURLs_Call {
	_c.Call.Return(run)
	return _c
}

// MockScraper_Expecter provides the type-safe EXPECT() API.
type MockScraper_Expecter struct {
	mock *mock.Mock
}

// EXPECT returns a MockScraper_Expecter for setting up type-safe expectations.
func (_m *MockScraper) EXPECT() *MockScraper_Expecter {
	return &MockScraper_Expecter{mock: &_m.Mock}
}

// NewMockScraper creates a new MockScraper instance with test cleanup registered.
func NewMockScraper(t interface {
	Cleanup(func())
	FailNow()
	Errorf(format string, args ...interface{})
	Logf(format string, args ...interface{})
}) *MockScraper {
	mock := &MockScraper{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
